name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify SSH key
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Error: SSH_PRIVATE_KEY secret is not set"
            exit 1
          fi

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        env:
          PIN: ${{ secrets.PIN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          ENTRY_TIMEOUT_HOURS: ${{ secrets.ENTRY_TIMEOUT_HOURS }}
        run: |
          if [ -z "${{ secrets.VPS_USER }}" ] || [ -z "${{ secrets.VPS_HOST }}" ]; then
            echo "Error: VPS_USER or VPS_HOST secrets are not set"
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            if [ ! -d "${{ vars.APP_PATH }}" ]; then
              git clone https://github.com/xyberty/snapbin.git ${APP_PATH}
            fi
            cd ${APP_PATH}
            # Create or update the .env file with the sensitive environment variables
            echo "PIN=${PIN}" > .env
            echo "MONGODB_URI=${MONGODB_URI}" >> .env
            echo "ENTRY_TIMEOUT_HOURS=${ENTRY_TIMEOUT_HOURS}" >> .env
            chmod 600 .env  # restrict file permissions for security

            # Pull the latest changes and rebuild your container
            git pull
            docker-compose build
            docker-compose up -d
          EOF
